local _g = {}
_g.callbacks = callbacks
_g.client = client

local _call = {}
_call.fire_event = "FireGameEvent"
_call.player_death = "player_death"

local _queue1 = {
    "Cousin marriage in the Arab world ranges from 8% in Morocco to 44% in Saudi Arabia.",
    "Arab Christians have lower rates of inbreeding than Arab Muslims.",
    "Inbreeding rates in Qatar, Yemen, the UAE, and other Muslim countries are increasing.",
    "25% of Egyptians support suicide bombings.",
    "36% of Muslims believe 9/11 was partially or wholly justified.",
    "Arab countries have the highest rates of inbreeding in the world.",
    "30% of Iraqis marry their cousins.",
    "62% of Palestinians support the use of suicide bombings.",
    "One in four Palestinians approves of attacks on US civilians in America.",
    "87% of Egyptians agree with Al Qaeda’s goals.",
    "78% of Egyptians support attacks on US soldiers in the Middle East.",
    "35% of Palestinians have a favorable opinion of Al Qaeda.",
    "One in eight Muslims worldwide has a favorable view of al Qaeda.",
    "1 in 3 Muslims favorably views Hamas, a terrorist organization.",
    "1 in 9 Arabs has a positive view of ISIS.",
    "Muslim countries produce so few patents that their contributions worldwide are “invisible”.",
    "Muslim nations spend 1/7 as much of their GDP on R&D as the rest of the world.",
    "Every Muslim nation produces less scientific research than the world average.",
    "The average Muslim nation produces less than 1/10 as much scientific research as a non-Muslim nation.",
    "Between 3% and 30% of Turkish college students believe honor killings are normal.",
    "1 in 3 Jordanian youth agree with honor killings.",
    "As many as 50% of rural Afghani men engage in pedophilia.",
    "16% of Turks support suicide bombings.",
    "More than half of Moroccans approve of attacks on American soldiers.",
    "The majority of Pakistanis grieved over Osama Bin Laden’s death.",
    "20% of Turks believe that the Charlie Hebdo cartoonists “got what they deserved” for insulting Islam.",
    "ISIS is supported by 11.5% of Arabs, or 42 million people.",
    "There is a “strong preference for first-cousin marriage in most Muslim countries”.",
    "74% of North African and Middle Easterners are anti-Semitic.",
    "Half of all Muslims are inbred.",
    "Hundreds of millions of Muslims reject freedom of religion and freedom of expression.",
    "The four countries with the highest rates of child marriage are all majority Muslim.",
    "As many as 300 million Muslims may support ISIS.",
    "ISIS support with Muslims globally ranges, conservatively, between 20-30% – as many as 500 million people.",
    "Rape of infidel women is part of Islamic law and Islamic tradition.",
    "62% of Canadian Muslims want Sharia law.",
    "More than 1 in 3 Canadian Muslims refuses to repudiate Al Qaeda.",
    "In 2008, 80% of Somali immigration to the United States was fraudulent.",
    "One in four young Muslims in America believes that terrorism is justified.",
    "One in twenty Muslim Americans favorably views Al-Qaeda.",
    "8% of American Muslims believe that Al-Qaeda’s beliefs are Islamic and correct.",
    "9% of Muslims in America believe that ISIS’s beliefs are Islamic and correct.",
    "11% of Muslims in America believe that Sharia law must be imposed worldwide through Jihad.",
    "33% of Muslims in America believe that Sharia law is greater than the Constitution.",
    "29% of Muslim Americans believe that violence against those who insult Islam is acceptable.",
    "One in four American Muslims believe that violence against Americans is acceptable as part of Jihad.",
    "16% of American Muslims defines Jihad as “violent holy war against unbelievers of Islam”.",
    "Immigration of Muslims to the West may increase terrorism and radicalization.",
    "Resettling refugees in the West is twelve times more expensive than caring for them in their own countries.",
    "Immigrants to the West have high rates of consanguinity (inbreeding).",
    "Immigration to Europe and North America has raised the amount of inbreeding in our countries.",
    "The more contact Americans have with Muslims, the more “Islamophobic” they are.",
    "Caring for one Middle Eastern refugee in America costs $64,370 over five years.",
    "90% of Middle Eastern immigrants to the United States do not pay income tax and receive money from the government.",
    "91.4% of refugees in America are on food stamps.",
    "65% of European Muslims believe that Sharia law is more important than the law of their country.",
    "European Muslims are 7.5x more likely to be fundamentalists than Christians.",
    "45% of European Muslims believe that Jews cannot be trusted.",
    "60% of European Muslims are explicitly homophobic. This is not due to poverty or education.",
    "The children of Muslim immigrants in Europe claim to face more discrimination than their parents.",
    "Migrants to Europe are twice as likely to be unemployed as White Europeans.",
    "Migrants to Europe are twice as likely to drop out of school as White Europeans.",
    "One of best predictors of crime among migrants to Europe is the prevalence of Islam in their home country.",
    "Support for terrorism among Muslims in Europe is increasing with newer generations.",
    "13% of Syrian ‘refugees’ support ISIS.",
    "ISIS-linked groups.",
    "75 to 80 percent of migrants entering Europe are military-age males in generally good health.",
    "“Two in every 100 Syrian migrants smuggled into Europe are ISIS-trained jihadists”.",
    "Non-White migrants in Europe account for one in three new HIV infections.",
    "There are few immigrants in German’s university-track high schools.",
    "Germany’s choice to accept migrants will cost at least 11 billion dollars.",
    "30% of ‘Syrian’ immigrants to Germany are fraudulent.",
    "Only 1 in 10 Muslims migrants arriving in Germany is employable.",
    "One in eight Muslims in Germany believes that terrorism is justified.",
    "Germany will be a Muslim Turkish nation by 2050 if demographic trends continue.",
    "3 million Turks came to Germany as “guest workers”, but 80% of them now live on welfare.",
    "Accepting a single refugee costs Germany $14,500 per year.",
    "80% of Muslim Turks in Germany are unemployed and live on welfare.",
    "70% of the children of Turks in Germany lack the equivalent of a high school degree.",
    "1 in 12 British schoolchildren is Muslim, and the Muslim population will increase for “many decades”.",
    "One in three British Muslims does not speak English.",
    "55% of Pakistanis in the UK are married to their cousins.",
    "British Pakistanis make up 3% of the population but 33% of genetically diseased children due to inbreeding.",
    "All available studies find that non-European immigrants to Britain cost about $10 billion/year.",
    "British Muslims are twice as likely as British Christians to be unemployed.",
    "Britain will become a Muslim country by 2050 if demographic trends continue.",
    "At least 85 legally binding Sharia courts operate in Britain.",
    "32% of Muslim university students in Britain believe that killing in the name of religion is acceptable.",
    "28% of British Muslims would like for Britain to become a fundamentalist Islamic state.",
    "68% of British Muslims support criminalizing criticism of Islam.",
    "3 out of 4 British Muslims support criminalizing drawings of Mohammed.",
    "9% of British Muslims define themselves as “hardcore Islamists”.",
    "Only 3% of British Muslims support free speech.",
    "0/500 British Muslims believe that homosexuality is morally acceptable.",
    "One in sixteen young Muslims in Britain believe honor killings are acceptable.",
    "18% of young Muslims in Britain believe honor violence is acceptable.",
    "Despite being less than 5% of the population, more than 20% of British prisoners are Muslim.",
    "Immigrants to Britain make up one fifth of rape and murder suspects.",
    "European migrants to the UK have improved public finances, while non-White immigration has cost money.",
    "30% of Muslims in Britain do not identify as British.",
    "4% of British Muslims live in free housing.",
    "More than 1 in 5 British Muslims claims to be disabled, higher than any other ethnic or religious group.",
    "40% of British Muslims want Sharia law.",
    "1 in 10 British Muslims supports honor killings.",
    "One in five British Muslims sympathize with the 7/7 terrorist attack.",
    "17,000 honor crimes take place every year in Britain.",
    "The number of honor crimes committed in Britain doubles every year.",
    "6% of Muslims in Britain are explicitly “disloyal” to Britain.",
    "24% of Muslims in Britain believe that violence against those who publish images of Muhammad is justified.",
    "45% of British Muslims believe that clerics preaching violence against the West are in line with mainstream Muslims.",
    "7% of Muslims in Britain believe that Muslims should not have to obey British laws.",
    "As many as 1.5 million British Muslims may sympathize with ISIS.",
    "21% of British Muslims believe that suicide attacks against the military can be justified.",
    "16% of British Muslims would be indifferent if a family member joined Al-Qaeda. 2% would be proud.",
    "7% of Muslims in Britain believe that suicide attacks in Britain can be justifiable.",
    "5% of British Muslims believe suicide attacks by Muslims against Britain’s are justified.",
    "18% of British Muslims think the Muslim community has done too much to integrate into British society.",
    "One in three young Muslims in Britain believes that terrorism is justified.",
    "4% of British Muslims do not believe the Holocaust happened.",
    "Most British Muslims do not believe that Muslims should participate in Holocaust remembrance.",
    "46% of British Muslims believe the Jews control the media and politics.",
    "37% of British Muslims believe British Jews are “legitimate targets” in the Israeli-Palestinian dispute.",
    "16% of British Muslims believe suicide bombings in Israel can be justified.",
    "7% of British Muslims believe suicide bombings against civilians can be justified.",
    "13% of Muslims in the UK believe attacks by Al-Qaeda on the United States as justified.",
    "11% of British Muslims believe suicide bombings against the police can be justified.",
    "9% of British Muslims believe suicide bombings against government workers can be justified.",
    "In the British city of Birmingham, only one in three students is White.",
    "38% of British Muslims believe that foreign Muslims who incite hatred should be allowed to stay in the UK.",
    "28% of British Muslims believe they bear little or no responsibility for rooting out religious extremism.",
    "5% of British Muslims would not tell anyone if a fellow Muslim was planning a terror attack.",
    "27% of Muslim students in the UK see a conflict between loyalty to the UK and loyalty to Muslims.",
    "10% of Muslim students in the UK wouldn’t report a Muslim planning terrorism to the police. 10% more refuse to answer.",
    "In Britain, Muslims make up 21% of youth criminals. Immigrants all together make up 45%.",
    "In Britain, more Muslims join ISIS than join the British army.",
    "Caring for one refugee for one year costs Britain £24,000.",
    "73% of Tuberculosis cases in Britain occur to people born outside the UK.",
    "80% of Tuberculosis cases in London occur to people born outside of the UK.",
    "7% of the British population backs ISIS.",
    "In the United Kingdom, there may be as many as 1 million victims of Muslim rapists.",
    "The income gap between native Swedes and immigrants to Sweden is growing.",
    "25% of crime in Sweden was committed by immigrants, and 20% more was committed by children of immigrants.",
    "Sweden is the rape capital of the West, likely due to immigration.",
    "85% of rapists in Sweden were non-Swedish immigrants.",
    "North African migrants to Sweden are 23 times more likely to rape than native Swedes.",
    "African migrants to Sweden are 16 times more likely to rape than ethnic Swedes.",
    "Iraqi migrants to Sweden are 2000% more likely to rape than native Swedes.",
    "16% of Swedish girls are not allowed to determine who they will marry.",
    "In Sweden, immigration has increased income inequality.",
    "One in four Swedish women will be raped in her lifetime.",
    "Immigrants to Sweden make 60% of what native Swedes earn, and this number has barely changed in 25 years.",
    "Immigration to Sweden is a net cost even in the long run.",
    "Sweden is the least successful nation at integrating immigrants in the world.",
    "African and Middle Eastern immigrants to Sweden with university degrees are less literate than Swedes without degrees.",
    "35% of immigrants to Sweden lack sufficient skills in both reading and math.",
    "Immigrants to Denmark are twice as likely as native Danes to commit violent crime.",
    "64% of children born to Arabs in Copenhagen are not “functionally literate”.",
    "Immigration to Denmark has on net cost billions of dollars.",
    "Because of inbreeding, children of Muslim immigrants to Denmark are three times more likely to be intellectually disabled than native Danes.",
    "More than half of rapists in Denmark are immigrants.",
    "77% of Muslims in Denmark believe that the Koran should be followed completely, an increase since 9 years ago.",
    "40% of Muslims in Denmark believe Sharia should be part of the country’s laws.",
    "One in ten Muslims in Denmark supports the exclusive rule of Sharia law in the country.",
    "In Copenhagen, 84% of people accused of serious crimes are immigrants.",
    "In Copenhagen, 90% of people accused of serious crime are non-citizens.",
    "The lifetime cost of non-European immigrants to Denmark is 2.5 million Kronar, or $450,000.",
    "Half of convicted rapists in Denmark are Muslims.",
    "Muslim are only 12% of France’s population but make up 70% of France’s prisoners.",
    "In France, 70% of burglaries are committed by first or second generation immigrants.",
    "In France, more than 40% of young Muslims believe that terrorism is justified.",
    "In France, 96% of rejected asylum seekers remain in the country.",
    "One in five young French Muslims believes that terrorism is often or sometimes justified.",
    "15% of French people back ISIS.",
    "40% of French Muslims do not have French friends.",
    "There are 751 Muslim ghettos in France.",
    "In France, 93% of Muslims vote for socialism.",
    "Second generation African and Asian immigrants to Norway have lower incomes than their parents.",
    "Immigrants to Norway from Africa or Southeast Asia are 3x more likely to commit crime than native Norwegians.",
    "Somalis in Norway are 4.4 times more likely to rape than native Norwegians.",
    "African immigrants to Norway are 3 times more likely to rape than ethnic Norwegians.",
    "The descendants of African immigrants to Norway are 60% more likely than their parents to commit crimes.",
    "The children of Asian immigrants to Norway are 80% more likely than their parents to commit a crime.",
    "Non-White immigrants in Oslo committed every rape from 2006 to 2010. 80% of the victims were Norwegian women.",
    "Immigrants to Norway retire on ‘disability’ sooner than do ethnic Norwegians.",
    "Norway’s immigration population more than doubled, from 5% to 12%, in just 10 years.",
    "Asian and African immigrants to Norway have “significantly” lower rates of employment than ethnic Norwegians.",
    "Humanitarian migration to Norway is “dominated by groups with poor qualifications”.",
    "The lifetime cost of a non-European immigrant to Norway is 4.1 million Krone, or $660,000.",
    "Caring for one refugee in Norway costs $24,000 per year.",
    "In Oslo, one in ten women over the age of 15 has been raped by Muslims.",
    "70% of Spain’s prisoners are Muslim, although Muslims are only 1.5% of the Spanish population.",
    "25% of Muslims in Spain believe that terrorism is justified.",
    "Spanish youth are more supportive of terrorism than their parents.",
    "Spain’s population of foreign-born people increased fivefold in 7 years.",
    "16% of young Muslim men in Belgium believe that terrorism is acceptable.",
    "In Belgium, the inbreeding rate among Muslim immigrants is continuing to remain high.",
    "In Ireland, immigrants account for one quarter of child abuse cases.",
    "Human evolution is not merely ongoing but is in fact accelerating.",
    "Human races are diverging into separate species, not mixing into one.",
    "The average H-1B immigrant is less intelligent and qualified than the average American.",
    "Immigration has reduced the average skill level of Americans.",
    "54% of college educated immigrants in America are not proficient in literacy.",
    "15% of the human genome has been under selective pressures since the races separated.",
    "Scientific discussion of race has increased since 1946 onwards.",
    "Melanin concentration may directly correlate with aggression.",
    "Race is a better predictor of crime than poverty.",
    "The purpose of section 8 housing is to move Blacks from elite urban areas to middle class suburbs.",
    "The percentage of Blacks and Hispanics in an area, not poverty, is the best predictor of crime.",
    "High income does not help Middle Eastern, East Indian and Asian men date White women.",
    "Women who claim to be willing to date any race are lying and are just as discriminatory as women with explicit racial preferences.",
    "Half of hate crimes are Blacks and Hispanics attacking each other.",
    "White and Asian women have more successful marriages than Black or Hispanic women.",
    "Blacks and Hispanics have less ability to delay gratification than Whites.",
    "Racism is an “automatic” part of human behavior.",
    "Men with high testosterone, who are also more attractive, are more likely to be racist.",
    "Of the 30 most deadly mass shootings in America, non-whites committed 36%, a slight overrepresentation.",
    "Most students accused of sexual assault on college campuses are non-White.",
    "White men are pound-for-pound stronger than Black or Hispanic men.",
    "Germanic/Nordic people have lower time preference than any other group.",
    "Asians, Hispanics and Blacks would rather live among White people than among other minorities.",
    "90% of gang members are non-White.",
    "Non-Jewish Whites are the most underrepresented group in top colleges.",
    "The Western aesthetic of big eyes and pale skin is universally considered appealing.",
    "There are more significant artistic figures from West than from the rest of the world combined.",
    "Europeans and Asians are subject to more recent evolution than Africans.",
    "48% of African Americans have Herpes Simplex Virus.",
    "Gonorrhea rates are 30 times higher in African Americans than in Whites.",
    "Police hesitate longer to shoot Black suspects than White suspects.",
    "Over 100 White women are raped or sexually assaulted by Black men every day in the United States.",
    "Blacks are overrepresented in serial killings, and this overrepresentation is increasing.",
    "Blacks are overrepresented among child abusers, and this isn’t due to biased reporting.",
    "39% of all cop killers are Black, although Blacks are only 12% of the population.",
    "73% of Black babies are born out of wedlock.",
    "The average Black has an IQ score 1 standard deviation (15 IQ points) lower than the average White.",
    "The Black-White IQ gap in America is equal to the gap in South Africa, even though SA is ruled by Blacks.",
    "The Black-White IQ gap exists even when both races are raised in identical environments.",
    "93% of Black men who are murdered are killed by other Black men.",
    "The Black-White IQ gap still exists and has not decreased in size.",
    "Blacks commit 56% of all robberies, despite being only 12% of the population.",
    "Blacks commit 50% of all murders, despite being only 12% of the population.",
    "Despite making up less than 12% of the US population, Blacks commit 1 in every 3 rapes.",
    "Young Black men kill 14 times more often than young White men.",
    "Africans have higher rates of a gene associated with violence.",
    "Black women are four times more likely to be overweight than White women.",
    "Blacks are seven times more likely than Whites to commit murder.",
    "Students of all races perform worse in schools with more Black students.",
    "Blacks have an average brain size of 1267 cubic cm, compared to Whites at 1347 cm.",
    "The percentage of Blacks in a city, not poverty, is the best predictor of crime.",
    "Blacks are 600% more likely than non-Blacks to commit murder.",
    "In New York City, 1% of people arrested for shootings were White, while 74% were Black.",
    "In New York City, 43% of people arrested for rape were Black.",
    "In New York City, 61% of people arrested for robbery were Black.",
    "Blacks have lower emotional intelligence than Whites.",
    "In Canada, Blacks comprise 2% of the population but 6% of prisoners.",
    "Blacks are more likely than Whites to be narcissistic.",
    "67% of people arrested for gun crime in London are Black, although Blacks are only 12% of the population.",
    "Black men in London are only 12% of the population, but commit 32% of rape.",
    "1 in four South African men has admitted to rape.",
    "Blacks are 90% more likely than Whites to be psychopathic.",
    "A Black person in Britain is twice as likely to be in jail as to be in university.",
    "70% of Ethiopian women report having been physically or sexually abused.",
    "Blacks are more prone to psychopathy and less capable of empathy than Whites.",
    "Blacks commit more violent crime against Whites than against other Blacks.",
    "Blacks are 39 times more likely to commit a violent crime against Whites than vice versa.",
    "Blacks are 136 times more likely to commit a violent crime against Whites than vice versa.",
    "Blacks are 2 times more likely to commit a hate crime against Whites than vice versa.",
    "Blacks are three times more likely than Whites to commit White-collar crime (fraud, bribery, racketeering, embezzlement).",
    "Areas with more Black people have higher rates of crime.",
    "Blacks assign less value to marriage than Whites.",
    "Blacks are significantly less likely than Whites to have harmonious or satisfying marriages.",
    "Blacks are more likely to default on loans than other races.",
    "Blacks are 80% more likely than Whites to neglect their children.",
    "Blacks are more likely to have ADHD than Whites.",
    "Blacks have less moral understanding that Whites.",
    "Blacks are more reckless than Whites.",
    "Blacks are twice as likely to subject their children to severe violence than Whites.",
    "Black men are four times more likely to beat their wives than White men.",
    "Black women are more than twice as likely as White women to abuse their husbands.",
    "Black youth are two and a half times as likely as White youth to have raped someone.",
    "In London, Blacks are six times more likely than Whites to be imprisoned.",
    "Blacks are more likely to kill their spouses than other races.",
    "Blacks are 50% more likely to cheat on their spouses than Whites.",
    "Blacks have less perseverance than other races.",
    "Black college students have poorer grades than students of other races with the same IQ.",
    "Blacks do less homework than Whites.",
    "Even after adjusting for SAT scores, Blacks have worse college grades than Whites.",
    "Blacks are four times as likely as Whites to murder their infants.",
    "Despite $1 trillion in aid from the West, per capita GDP in Africa has declined since 1960.",
    "Only 12% of Black eighth grade males are proficient in math.",
    "Academically, the average poor White male does as well as Blacks who aren’t in poverty.",
    "Only 12% of Black fourth grade males are proficient in reading.",
    "85% of crime between Blacks and Whites is committed by Blacks.",
    "Blacks are more likely than other races to be gay or bisexual.",
    "In just two years, more blacks were killed by other blacks than died from 80 years of lynching.",
    "Blacks are just 13% of the American population but have committed half of all murders for the last 30 years.",
    "Europeans have been awarded 540 Nobel prizes. Africans have been awarded one.",
    "Blacks are 60-80% more likely than Whites to lie about how much crime they commit.",
    "Black immigrants to Western Europe are “markedly” more likely to have schizophrenia than White people.",
    "Blacks are twice as likely to be schizophrenic than Whites, even after adjusting for income.",
    "Black men are more likely to lie about drug use than White men.",
    "Blacks are six times more likely to lie about their cocaine usage than White people.",
    "In Britain, Black people are six times more likely than Whites to be schizophrenic.",
    "90% of interracial violence between blacks and Whites is committed by Blacks. The ration should be 1-1.",
    "Black men are over a hundred times more likely to rape a White woman than vice versa.",
    "Most South Africans believe that life was better under apartheid.",
    "Life expectancy in South Africa has decreased since apartheid ended.",
    "The South African murder rate is the 10th highest in the world. White farmers are killed 4x more often than the general population.",
    "Blacks in South Africa are not indigenous inhabitants, but rather arrived just before White explorers.",
    "In South Africa, a child is raped every three minutes (175,000 children/year).",
    "In urban areas of South Africa, more than one in three men has admitted to committing rape.",
    "In South Africa, rape is seen as “a legitimate activity” and committed out of boredom.",
    "In South Africa, 7% of men have participated in gang rape.",
    "In South Africa, 78% of men have committed violence against women.",
    "“Out of the 1500 [chess] grandmasters in the world, only three or four are black.”",
    "Only 54% of Black men between 25-34 have high school degrees, are employed, and are not currently incarcerated.",
    "Unlike all other world cultures, sub-Saharan Africans had no mythologies regarding the stars or night sky.",
    "Sub-Saharan Africans are the only group of people without detailed mythology or creation stories.",
    "Half of Black women have herpes. 80% who have it don’t know it.",
    "1200 people, mostly blacks, die over sneakers every year.",
    "White-Asian children are twice as likely as Asians to have mental illness.",
    "“Nonwhite daters gain status by dating any White. Whites, on the other hand, have little to gain by dating minorities.”",
    "White/Black babies are less healthy than White babies.",
    "Mixed race couples are more likely to have stillborn babies than same-race couples.",
    "Black-White children are more likely than both Black and Whites to make poor decisions.",
    "90% of women who have a child with a Black man never marry the father.",
    "77% of women who have children with Black men earn less than $10,000 a year.",
    "98% of White women who have children with Black men are not financially supported by the father.",
    "The average White woman who has kids with a Black man earns $7250 a year, excluding welfare.",
    "97% of White women who have children with Black men have used welfare.",
    "97% of Black fathers who have children with White women are not active in their children’s lives.",
    "Race-mixers may give less parental support to their children because of greater genetic distance.",
    "97% of interracial (Black man, White women) children are born out of wedlock.",
    "White-Black couples have more partner violence than White couples and as much violence as Black couples.",
    "Bias against miscegenation is likely biological in origin.",
    "Interracial marriages have a 23.5% chance of divorce, compared to 13% for same-race couples.",
    "Mixed race kids suffer from low self-esteem, social isolation, and poor family dynamics.",
    "Mixed race children are more likely to have health problems, high stress, smoke, and drink.",
    "Interracial couples devote less time to maintaining their household than same race couples.",
    "Asians who marry outside of their race are less educated than Asians who do not.",
    "90% of White women who have kids with black men are unemployed or earn less than 10K a year.",
    "White women who marry minorities tend to be poor and to “marry up” in socioeconomic status.",
    "Slim, slender, athletic, fit or average White women are 7x more likely than fat White women to refuse to date Blacks.",
    "Better educated men and women are more likely to exclude blacks as romantic partners.",
    "40% of Asian women refuse to date Asian men.",
    "Asian women find White men more attractive than Asian men.",
    "Asians are nine times more likely than Whites to be members of gangs.",
    "Evidence indicates Asians have genetically less individuality and more conformity than White people.",
    "Asians are more likely to default on financial obligations than Whites.",
    "Between one in three and one five urban Korean women have had plastic surgery.",
    "Half of young Korean women have had plastic surgery.",
    "Koreans are more concerned with physical appearance than Westerners.",
    "64% of Hispanics have IQ scores too low to enter the military.",
    "Hispanics receive shorter prison sentences than Whites for the same crimes.",
    "Hispanics are imprisoned at a rate 2.9 times that of White people.",
    "The children of Hispanic immigrants have a higher crime rate than the immigrants themselves.",
    "Mexicans born in the United States are more likely to be born out of wedlock than Mexicans born in Mexico.",
    "48% of Hispanics are born out of wedlock, double the rate of illegitimate White births.",
    "On any given day, there are between 30,000 and 45,000 illegal aliens in the nation’s prisons and jails.",
    "Non-citizen Hispanics are 29% of the federal prison population, despite only being 5% of the population.",
    "Immigrants are four times more likely than native-born Americans to fail to graduate high school.",
    "Hispanic illegal aliens are only 5% of America’s population but 25% of drug offenders.",
    "Hispanic immigration has displaced African Americans and raised the Black crime rate.",
    "Hispanics are 19 times more likely than Whites to be a gang member.",
    "Hispanics are three times more likely to be in prison than Whites.",
    "Hispanics are three times as likely as Whites to commit violent crime.",
    "In America, non-citizen Hispanics are overrepresented among white collar crimes.",
    "Hispanics are 60% more likely than Whites to neglect their children.",
    "In New York City, 45% of people arrested for rape were Hispanic.",
    "The share of college degrees earned by Hispanics, already very low, has not changed in two decades.",
    "The Hispanic high school drop out rate of 50% is unchanged across generations.",
    "Because of demographic changes and low college attendance among Hispanics, per capita income in California is expected to decline.",
    "50% of Hispanic children are born out of wedlock, and this rate is rising rapidly.",
    "In Canada, Amerindians comprise 3% of the population but 18% of the prison population.",
    "Native Americans are more prone to psychopathy and less capable of empathy than any other race.",
    "Native Americans are more likely than other races to have committed violent assaults.",
    "Native American men are twice as likely as White men to beat their wives.",
    "Native Americans are more likely to be unemployed than any other race.",
    "Native Americans are four times as likely as Whites to commit infant homicide.",
    "Aboriginal Australians make up 2% if the Australian population but 27% of prisoners.",
    "Maori natives are 15% of the population but account for half of New Zealand’s prisoners.",
    "Gypsies are 5% of Britain’s prisoners but only .1% of Britain’s population.",
    "Jews are overrepresented in top colleges relative to their academic achievements.",
    "75-80% of art dealers, curators, and critics are Jewish.",
    "Alleles harmful to health are more common in Ashkenazi Jews than in the general population.",
    "The average Gypsy has an IQ below 80.",
    "70% of Irish travellers, also known as gypsies, are unemployed.",
    "Gypsies are .5% of the Irish population but commit 4.4% of child neglect.",
    "Cousin marriage and uncle-niece marriage are common in many Sephardic Jewish communities.",
    "Native Americans have an average IQ of 87.",
    "In Britain, Gypsies make up .1% of the population but 10% of serious youth criminals.",
    "Jews are 10% of Princeton’s students, an overrepresentation of 500%.",
    "Jews are between one quarter and one third of Ivy League college students.",
    "At Ivy League colleges, Jews are overrepresented and minorities are proportionally represented.",
    "In 1934, Jews held 38.5% of senior Soviet security posts.",
    "Women are less likely to be employed in highly competitive jobs.",
    "More prosperous, egalitarian and healthy nations have more psychological differences between men and women.",
    "More advanced societies have more differentiated gender roles.",
    "Women commit about half of domestic violence.",
    "Wealthier countries have more developed sex roles.",
    "For women, more sex partners results in higher rates of divorce and worse life outcomes.",
    "Women with more than 20 sexual partners have an 80% chance of divorce.",
    "More sex partners causally increases the likelihood of drug and alcohol abuse.",
    "Men’s’ and women’s’ brains are wired differently.",
    "Gender stereotypes are correct predictors of math and reading ability.",
    "A women’s number of sex partners is linearly linked to alcohol and drug abuse.",
    "College students who major in fields with a greater proportion of women have lower average IQ.",
    "Less attractive women are more likely to want careers.",
    "Less traditional marriages are lower quality.",
    "Couples who cohabit before marriage have lower quality marriages.",
    "Gender differences in the West are the result of free choices made by innately different men and women.",
    "40% of women with more than 20 sex partners have an STD.",
    "Female veterans are six times more likely to commit suicide than women who didn’t serve in the military.",
    "Progressive/feminist women are less happy than their peers.",
    "Stay-at-home wives are more content than working wives.",
    "Women are less happy today than they were in the 1960’s and 70’s.",
    "Couples with traditional gender roles are more sexually active than couples with egalitarian roles.",
    "Claims that gay parents are just as capable of raising children as straight parents are misrepresented.",
    "Between 24% and 90% of lesbians report being psychologically abused by their partners.",
    "Gay men are 60x more likely to have HIV than straight men.",
    "46% of male homosexuals report being molested, as compared to only 7% of heterosexual men.",
    "Gays are more likely than straight people to have mental illness.",
    "1/4 gay men in America have had over 1000 sex partners.",
    "43% of gay men have over 500 partners.",
    "Gay men are six times more likely to commit suicide than straight men.",
    "Gay men are 12x more likely to use amphetamines than straight men.",
    "Gay men are 10x more likely to use heroin than straight men.",
    "Liberal arguments in favor of homosexuality are based on logical fallacies.",
    "10 to 15 percent of older homosexuals have more than 1000 sex partners.",
    "Gay people are 2-3x more likely to abuse alcohol than straight people.",
    "Up to 50% of lesbians have reported sexual abuse.",
    "79% of homosexual men say over half of their sex partners are strangers.",
    "99.8% of lesbian, gay and bisexual teens will change their sexual orientation within 13 years.",
    "Two-thirds of men and women who were homosexual change their orientation to heterosexual five years later.",
    "Two thirds of self-identified lesbians later have heterosexual relationships.",
    "Identifying as lesbian, gay or bisexual does not end sexual questioning or confusion.",
    "One in eight gay men in London has HIV.",
    "Gay men are twice as likely as straight men to be in interracial relationships.",
    "In Australia, 25% of homosexuals have had more than 100 sex partners.",
    "Gay men, who are 1.65% of the US population, account for 63% of the country’s syphilis cases.",
    "In 2010, homosexuals were about 200 times more likely than everyone else to be diagnosed with HIV.",
    "Gay men are 15 times more likely to have Hepatitis B than everyone else.",
    "Homosexuals are more to use illegal drugs and drink to excess than straight people.",
    "Homosexuals are more likely than straight people to have anxiety, depression, bipolar disorder, and to commit suicide.",
    "Gay men are 10-15 times more likely than straight men to have eating disorders.",
    "40% to 60% of serial killers are homosexuals.",
    "Homosexual men are more likely to have been abused by their partners than straight men.",
    "Monogamy is not a central feature of most homosexual relationships.",
    "Married homosexual men are 50% more likely than straight couples to divorce.",
    "In the Netherlands, the average homosexual in a “steady relationship” has seven to eight affairs per year.",
    "Over 20% of older homosexuals have had more than 500 different sex partners.",
    "The average gay man has several dozen sex partners per year.",
    "28% of homosexuals have had sex with over a thousand men. For straight men? Just 25% have had sex with more than 10 women.",
    "Most “long term relationships” between gay men last less than eight years.",
    "Among gay Canadian men in “committed relationships, only 25% were monogamous.",
    "In one study, only 9% of gay men were monogamous.",
    "75% of straight men an are faithful, compared to just 4.5% of gay men.",
    "In Berlin, 83% of gay men in “steady” relationships had had frequent affairs in the last year.",
    "Infection rates for gonorrhea and chlamydia are increasing among active homosexual men.",
    "Gay men, 1% of the population, account for 83% of syphilis cases.",
    "Syphilis was almost eradicated, but made a comeback among homosexual men.",
    "Active homosexual men are 17 times more likely than straight people to have anal cancer.",
    "Lesbians are 2.5x more likely than straight women to be obese.",
    "Lesbians are twice as likely as straight women to have eating disorders.",
    "Lesbians are twice as likely as straight women to be stalked or physically abused by their partners.",
    "Married lesbians are 2-3 times more likely to divorce than straight couples.",
    "Homosexuals, lesbians, and transsexuals are poorer than straight people.",
    "America has spent $700 million promoting gay rights abroad – an “integral” part of American foreign policy.",
    "Transsexuals are four times more likely than the average person to be infected with HIV.",
    "About 88% of children who have gender dysphoria do not hold those beliefs when they grow older.",
    "Only 12% of boys who believe they are transsexuals still believe so when they are older.",
    "MRI scans indicate that MtF transsexuals are either men aroused by the thought of possessing female genitalia or homosexuals who want to seduce straight men.",
    "41% of transsexuals have tried and failed to commit suicide.",
    "Transsexuals who undergo sex reassignment surgery are more likely to commit suicide.",
    "Most young transsexuals have committed self-harm within the last twelve months.",
    "65% of transsexual youth have seriously considered suicide within the last year.",
    "37% of transsexual youth have attempted suicide within the last year.",
    "1 in 10 young transsexuals has attempted suicide more than three times in the last year.",
    "Only 21% of transsexuals can sucessfully pass as the opposite gender.",
    "53% of mothers of transsexual children have Borderline Personality Disorder, compared to only 6% of mothers of normal children.",
    "16% of transsexuals have been sent to jail or prison, compared to 2.7% of the general population.",
    "Gay and transgender students are half as likely to graduate high school as straight students.",
    "20-40% of homeless children are transsexuals.",
    "Children raised by gay couples are twice as likely to be in poverty as children of straight married couples.",
    "“24% of lesbians and bisexual women are poor, compared with only 19% of heterosexual women.”",
    "1/3 transsexuals are being treated for mental health.",
    "85% of transsexuals show signs of psychological distress or have been recently treated for mental health.",
    "44% of transsexuals show signs of clinical depression.",
    "Transsexuals are more likely to have autism than the general population.",
    "Transsexuals college students are five times more likely than all students to have an eating disorder.",
    "Transsexuals college students are 30 times more likely than straight men to have eating disorders.",
    "27% of MtF transsexuals test positive for HIV. Only 12% report it.",
    "Transsexuals are several times more likely than normal people to have schizophrenia.",
    "Worldwide, male-to-female transsexuals are 50 times likely to have HIV than normal people.",
    "Transsexuals have higher rates of drug and alcohol abuse, prostitution, and incarceration than normal people.",
    "Transsexuals have higher rates of unemployment, homelessness, and attempted suicide than normal people.",
    "Transsexuals are four times more likely to live in extreme poverty than the general population.",
    "Transsexuals are twice as likely to be unemployed as the general population.",
    "Non-white transsexuals are four times as likely to be unemployed as the general population.",
    "Transsexuals are twice as likely to be homeless as cisgendered people.",
    "1 in 5 transsexuals has been homeless at least once in their lives.",
    "Close to 80% of children who feel transsexual will abandon their sexual confusion as they age.",
    "Many transsexuals choose to take hormone treatments over HIV medication.",
    "Male-to-female transsexuals are 50 times more likely than normal people to have HIV.",
    "Liberal men are more willing to date non-Whites.",
    "Less masculine men are more prone to violence.",
    "Muscular strength increases self-esteem and decreases depression, suicide, and hopelessness.",
    "Weaker men are more liberal than stronger men.",
    "“Men run larger, more innovative, and more growth-oriented enterprises than their female counterparts.”",
    "Men are three times more effective at committing suicide than women.",
    "Weaker men are genetically more likely to support redistribution.",
    "Women with low waist-to-hip ratios produce smarter children.",
    "Blind men have statistically identical body standards as sighted men.",
    "Attractive and successful women are more likely to be heterosexual.",
    "Attractiveness is about 80% shared and 20% in the eye of the beholder.",
    "There is a biological basis in a portion of the brain for objective beauty.",
    "More diverse neighborhoods have lower social cohesion.",
    "Diversity increases psychotic experiences.",
    "Diversity increases social adversity.",
    "A 10% increase in diversity doubles the chance of psychotic episodes.",
    "Diversity reduces voter registration, political efficacy, charity, and number of friendships.",
    "Ethnic diversity reduces happiness and quality of life.",
    "Diversity reduces trust, civic participation, and civic health.",
    "Ethnic diversity harms health for Hispanics and Blacks.",
    "Diversity primarily hurts the dominant ethnic group.",
    "Ethnic diversity reduces concern for the environment.",
    "Ethnic diversity within 80 meters of a person reduces social trust.",
    "Ethnic diversity directly reduces strong communities.",
    "Ethnically homogeneous neighborhoods are beneficial for health.",
    "In America, more diverse cities have more segregation.",
    "Homogeneous polities have less crime, less civil war, and more altruism.",
    "States with little diversity have more democracy, less corruption, and less inequality.",
    "There is extensive evidence people prefer others who are genetically similar.",
    "Borders, not multiculturalism, reduce intergroup violence.",
    "Diversity reduces charity and volunteering.",
    "People who live in diverse communities rather than homogenous ones are poorer and less educated.",
    "Black people trust their neighbors less than do White people.",
    "Spanish speakers trust their neighbors less than do English speakers.",
    "Asians trust their neighbors less than do White people.",
    "Ethnically diverse workplaces have lower cohesion, lower satisfaction and higher turnover.",
    "Ethnic diversity reduces social trust.",
    "Ethnic diversity among members of the same race reduces infrastructure quality, charity, and loan repayment.",
    "Diversity of any sort makes people more likely to defect in game theoretic scenarios.",
    "Homogeneous military units have less desertion than diverse units.",
    "Diversity correlates with low GDP.",
    "Ethnic homogeneity correlates with strong democracy.",
    "Genetic diversity causes societal conflict.",
    "Ethnic diversity causally decreases social cohesion.",
    "Ethnocentrism is rational, biological, and genetic in origin.",
    "Babies demonstrate ethnocentrism before exposure to non-Whites.",
    "Ethnocentrism is universal and likely evolved in origin.",
    "Races are extended families. Ethnocentrism is genetically rational.",
    "Ethnocentrism is biological in origin and a superior evolutionary strategy to altruism.",
    "Humans are more altruistic to individuals who they are more closely related to.",
    "People subconsciously prefer those who are genetically similar to them for biologically rational reasons.",
    "Kinship between members of an ethnic group is greater than expected.",
    "Human intelligence is highly heritable.",
    "The scientific consensus is that IQ tests are not racially biased.",
    "Very poor Whites are about as intelligent as very wealthy Blacks.",
    "Privately, intelligence experts hold more hereditarian views than they express in public.",
    "Black children raised in White households have similar IQ scores to Black children in Black households.",
    "The average African IQ is estimated at 75.",
    "The average African-American IQ is 85, compared to the average White IQ of 100.",
    "The White-Black gap in SAT scores, a proxy for IQ, is increasing.",
    "Genes for large brains, linked to high IQ, are common everywhere except Africa.",
    "Intelligence has a 40-50% genetic basis.",
    "IQ scores are the best predictor of success in Western society.",
    "IQ is 75% heritable among Whites.",
    "The average Hispanic IQ is 90.",
    "The average IQ in Sub-Saharan Africa is 70.",
    "The average IQ in southeast Asia is 87.",
    "The heritability of IQ reaches .8 (80%) in later adulthood.",
    "Intelligence “is one of the best predictors of important life outcomes such as education, occupation, mental and physical health and illness, and mortality.”",
    "Intelligence is the most important trait for marriage.",
    "Heritability of IQ increases throughout life (except for very old age).",
    "The Black-White IQ gap is mostly heritable.",
    "Higher IQ is linked to lower time preference.",
    "The IQ of a country’s rulers largely determines productivity and wealth.",
    "Intelligent people are more likely to be physically active outside of work and to eat fruits and vegetables.",
    "Everyday life is an IQ test.",
    "“Intelligence and ability are personal traits that are stable over time and that the role of effort in academic performance is limited.”",
    "Stereotype effect explains a just “small to medium” amount of group differences in IQ.",
    "A meta-analysis concludes that stereotype threat predicts 3.3 IQ points of group differences in intelligence.",
    "There is pervasive publication bias in research claiming that “stereotype threat” is responsible for group differences in intelligence.",
    "When corrected for publishing biases, the impact of stereotype threat is statistically indistinguishable from zero.",
    "The world’s thirty least intelligent countries (except for Haiti) are all in sub-Saharan Africa.",
    "Haiti, Nepal, Sri Lanka, Guatemala and Qatar are the least intelligent countries outside of sub-Saharan Africa.",
    "Colder climates selected for higher IQ populations by imposing more complex survival requirements.",
    "Higher IQ is linked to more democracy.",
    "IQ is the best known predictor of job performance for all studied occupations.",
    "Intelligence can be measured directly from brain scans, without tests of any sort.",
    "The average criminal has an IQ of 85.",
    "Most if not all psychological traits are substantially influenced by genetics.",
    "IQ scores predict life outcomes equally well for different races.",
    "Muslim counties have an average IQ of just 81, 7.5 points lower than non-Muslim countries.",
    "Arab countries have an average IQ of just 84.",
    "Skin color is the best biological predictor of IQ.",
    "Nearly every reliably measured psychological trait, especially IQ, is significantly influenced by genetic factors.",
    "Smarter people are more cooperative than dumb people.",
    "Humans can be genetically categorized into five racial groups, corresponding to traditional races.",
    "Genetic analysis “supports the traditional racial groups classification.”",
    "“Human genetic variation is geographically structured” and corresponds with race.",
    "Race can be determined via genetics with certainty for >99.8% of individuals.",
    "Oral bacteria can be used to determine race.",
    "Race can be determined via brain scans.",
    "96-97% of Whites have no African ancestry.",
    "97% of Whites have no Black ancestry whatsoever.",
    "There was minimal gene flow between archaic Europeans and Asians.",
    "Common-sense racial categories have biological meaning.",
    "A substantial amount of the human genome has been subjected to natural selection since the races diverged.",
    "With 160 short gene sequences, race can be determined with 100% accuracy for Whites, Asians, and Africans.",
    "Principal continent of origin (race) can be determined with 87% accuracy even for highly mixed populations.",
    "“It is inaccurate to state that race is biologically meaningless.”",
    "Race is biologically real and represents “genetic clusters” of variation.",
    "“Empirical structure within human genetic variation …resembles continentally based racial classifications”.",
    "“Recent research in genetics demonstrates that certain racial, and also ethnic, categories have a biological basis in statistically discernible clusters of alleles.”",
    "“Numerous human population genetic studies have come to the identical conclusion that genetic differentiation is greatest when defined on a continental basis.”",
    "Genetic analysis of race corresponds with self-identification more than 99% of the time.",
    "Races are human subspecies.",
    "The “social constructionist account of race lacks biological reality”.",
    "Race can be determined from fingerprints.",
    "For 99.86% of individuals, genetic analysis of race matches self-identification.",
    "Predefined ethnic/racial labels are “highly informative” about genetic identity.",
    "Over 2000 genes have been subject to recent (post out-of-Africa) evolution.",
    "The concept of race existed in ancient Greece, Rome, Egypt, China, India, and Arabia.",
    "Racial classification has genetic significance.",
    "Racial identity is real and is hidden in correlations between different traits.",
    "With enough data points, an individual will never be closer related to someone of another race than someone of their own race.",
    "An individual’s geographic origin can be determined from their genes “with remarkable accuracy”.",
    "The more liberal someone is, the more likely they are to unjustly discriminate on the basis of politics.",
    "Conservative psychologists face discrimination that liberals do not notice.",
    "82% of psychologists are explicitly willing to discriminate against conservatives.",
    "The field of psychology is rife with progressive bias and intolerance of conservatives.",
    "Liberals are equally as intolerant as conservatives.",
    "Conservatives are happier than liberals.",
    "Liberals consistently underestimate the compassion of conservatives.",
    "Liberals view themselves as more compassionate than they really are.",
    "Young people who advocate for social justice are less tolerant than their peers.",
    "Conservative and rural Whites are discriminated against in college admissions.",
    "Liberals value the lives of Black people and foreigners more than the lives of White people and Americans.",
    "72% of American college faculty are liberal, while only 15% are conservative.",
    "American colleges, 87% of faculty identify as liberal.",
    "Southern cities, corrected for race and poverty, have less crime than other American cities.",
    "Sweden’s Human Development Index is expected to decline.",
    "The diversity of hair and eye color among Whites is an evolutionary adaptation.",
    "1% of Sweden’s population is responsible for 63% of their crime.",
    "Homicide rates would be 5x higher today if not for medical advancements.",
    "Assimilation into a host culture improves well-being.",
    "Traditional societies have ‘very low’ rates of suicide.",
    "Human evolution is unceasing and continues to this day.",
    "Higher individuality is linked to lower time preference.",
    "Extensive use of the death penalty historically in Europe is responsible for today’s peace and low crime.",
    "Morally repugnant hypotheses are incorrectly viewed as less plausible.",
    "Remembering your ancestors increases intellectual performance.",
    "Human evolution took place as recently as 500 generations ago.",
    "All behavioral traits are substantially heritable. Evidence for this is “ubiquitous”.",
    "Seeing the American flag increases nationalism.",
    "Racial, religious, gender, and other stereotypes are generally accurate.",
    "Stereotypes are generally accurate, and prejudice relatively small and fleeting.",
    "Poorly performing schools often receive equal or more funding than well-performing schools.",
    "100% (324/324) of Chinese researchers believe race is biologically real.",
    "Jews, Blacks, and women were instrumental in turning the scientific consensus against the validity of race.",
    "Americans soldiers have higher IQ scores than civilians.",
    "Violence is a heritable trait.",
    "Offensive words do not cause harm.",
    "Internet access increases racial animosity.",
    "73% of India’s population, or over 900 million people, would move to the United States if able (i.e., open borders).",
    "In Europe, culture corresponds closely to genetic group.",
    "Feudal Britain had eugenic natural selection for rich individuals.",
    "In most countries, immigration reduces the academic performance of native schoolchildren.",
    "Between 2 and 6 percent of illegal immigrants voted in the 2008 and 2010 elections.",
    "Immigration will reduce the average IQ of countries and lead to the collapse of Western civilization.",
    "99% or more of adolescents who attempt to commit suicide fail.",
    "Nordic countries “have long played a disproportionate role on issues of global development.”",
    "More religious people have better quality marriages.",
    "Households with a single mother and a non-biological father have the highest rates of child abuse and neglect.",
    "Poverty is not a cause of crime.",
    "Concealed carry holders commit less gun crime than even police officers.",
    "Stereotypes are accurate, and this is one of the strongest findings in the field of psychology.",
    "Wealthier Americans are more authoritarian and more likely to oppose democracy than poor Americans.",
    "Worldwide, people are becoming less supportive of democracy and more amenable to non-democratic rule.",
    "Americans are becoming less supportive of democracy over time.",
    "Young Americans are less supportive of democracy than their parents.",
    "40% of wealthy Americans reject democracy and would support a strong autocrat.",
    "Immigration to the United States has increased income inequality.",
    "Across many different cultures, people want traditional landscape art the most and modern art the least.",
    "2.3% of Jews are inbred."
}

local _queue2 = {
}

_g.client.AllowListener(_call.player_death)
_g.callbacks.Register(_call.fire_event, function(event)
    if not event or event:GetName() ~= _call.player_death then
        return
    end

    local victim = _g.client.GetPlayerIndexByUserID(event:GetInt("userid"))
    local attacker = _g.client.GetPlayerIndexByUserID(event:GetInt("attacker"))

    if (victim == attacker or attacker ~= _g.client.GetLocalPlayerIndex()) then
        return
    end

    if (#_queue1 == 0) then
        _queue1, _queue2 = _queue2, _queue1
    end

    local index = math.random(#_queue1)
    local message = _queue1[index]
    table.remove(_queue1, index)
    table.insert(_queue2, message)

    _g.client.ChatSay(_queue1[math.random(#_queue1)])
end)
